version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    working_directory: ~/dockerfiles
    environment:
      DOCKER_VERSION: "17.03.0-ce"
      SUBDIRS: "zerotier zoneminder debian-arm alpine-bash-git"
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Docker client
        command: |
          apt-get -qq update
          apt-get install -y curl ca-certificates git
          curl -sSL -o "/tmp/docker-${DOCKER_VERSION}.tgz" "https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz"
          tar -xz -C /tmp -f "/tmp/docker-${DOCKER_VERSION}.tgz"
          mv /tmp/docker/* /usr/bin
    - run:
        name: Build images
        no_output_timeout: 35m
        command: |
          tag=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd-%h")
          for dir in *; do
            if [[ -f ${dir}/Dockerfile ]]; then
              image="ivan4th/${dir}:${tag}"
              echo "*** Building ${image} ***"
              docker build -t "${image}" "${dir}"
            fi
          done
    - run:
        name: Push images
        command: |
          tag=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd-%h")
          docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
          for dir in ${SUBDIRS}; do
            if [[ -f ${dir}/Dockerfile ]]; then
              image="ivan4th/${dir}:${tag}"
              echo "*** Pushing ${image} ***"
              docker push "${image}"
            fi
          done
